"""Generate LaTeX table fragments for report/report.tex.

Reads results/metrics/results.csv and writes:
  report/tables/main_results.tex      - the big test-set table
  report/tables/multi_vs_global.tex   - paired MAE delta per model/horizon
  report/tables/per_station.tex       - per-station MAE for the best
                                        sequence model (multi, h=1)

Also copies all PNGs from results/figures/ into report/figures/ and
creates small placeholder PNGs for any figure that hasn't been
generated yet, so pdflatex doesn't fail mid-build.

Usage:
    python -m src.make_latex_tables
"""
import shutil

import numpy as np
import pandas as pd

from . import config


REPORT_DIR     = config.PROJECT_ROOT / "report"
TABLES_DIR     = REPORT_DIR / "tables"
REPORT_FIG_DIR = REPORT_DIR / "figures"
TABLES_DIR.mkdir(parents=True, exist_ok=True)
REPORT_FIG_DIR.mkdir(parents=True, exist_ok=True)


# Mapping from internal model name -> what we want to print in the table.
MODEL_LABEL = {
    "persistence":     "Persistence",
    "linear":          "Ridge",
    "rf":              "Random Forest",
    "gbm":             "Gradient Boosting",
    "lstm":            "LSTM",
    "gru":             "GRU",
    "transformer":     "Transformer",
    "gru_tuned":       "GRU (tuned)",
    "lstm_tuned":      "LSTM (tuned)",
    "transformer_tuned": "Transformer (tuned)",
}
SETTING_LABEL = {"global": "global", "multi": "multi-site"}

# Order rows show up in the tables
MODEL_ORDER = [
    "persistence", "linear", "rf", "gbm",
    "lstm", "gru", "transformer",
    "lstm_tuned", "gru_tuned", "transformer_tuned",
]
SETTING_ORDER = ["global", "multi"]


def fmt(x, spec=".2f"):
    if pd.isna(x):
        return "--"
    return f"{x:{spec}}"


def write_main_results(df, out_path):
    """The big headline table: rows = models, column groups = (setting, h),
    sub-columns = MAE / RMSE / R^2 / spike_recall."""
    test = df[df["split"] == "test"].copy()
    horizons = sorted(test["horizon"].unique())
    settings = [s for s in SETTING_ORDER if s in test["setting"].unique()]
    metrics  = [("MAE", ".2f"), ("RMSE", ".2f"), ("R2", ".3f"), ("spike_recall", ".2f")]

    # Find best value per (setting, horizon, metric) so we can bold them
    best = {}
    for setting in settings:
        for h in horizons:
            sub = test[(test["setting"] == setting) & (test["horizon"] == h)]
            for metric, _ in metrics:
                if metric in ("MAE", "RMSE"):
                    best[(setting, h, metric)] = sub[metric].min()
                else:
                    best[(setting, h, metric)] = sub[metric].max()

    col_groups = [(s, h) for s in settings for h in horizons]
    n_sub = len(metrics)

    lines = []
    lines.append("% Auto-generated by src/make_latex_tables.py")
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(r"\caption{Test-set performance for every model, input setting, and "
                 r"horizon. Lower MAE/RMSE is better; higher $R^2$/spike-recall is better. "
                 r"Bold marks the best entry within each (setting, horizon, metric) column.}")
    lines.append(r"\label{tab:main}")
    lines.append(r"\setlength{\tabcolsep}{3pt}\small")
    col_spec = "l" + ("|" + "c" * n_sub) * len(col_groups)
    lines.append(rf"\begin{{tabular}}{{{col_spec}}}")
    lines.append(r"\toprule")

    # Top header row
    header = [""]
    for s, h in col_groups:
        header.append(rf"\multicolumn{{{n_sub}}}{{c}}"
                       rf"{{\textbf{{{SETTING_LABEL[s]}, $h{{=}}{h}$}}}}")
    lines.append(" & ".join(header) + r" \\")

    # cmidrule under each group
    cms = []
    pos = 2
    for _ in col_groups:
        cms.append(rf"\cmidrule(lr){{{pos}-{pos + n_sub - 1}}}")
        pos += n_sub
    lines.append(" ".join(cms))

    # Sub-header: metric names
    sub_header = [r"\textbf{Model}"]
    for _ in col_groups:
        for m, _ in metrics:
            sub_header.append(m.replace("R2", "$R^2$"))
    lines.append(" & ".join(sub_header) + r" \\")
    lines.append(r"\midrule")

    models_present = [m for m in MODEL_ORDER if m in test["model"].unique()]
    for model in models_present:
        row = [MODEL_LABEL.get(model, model)]
        for s, h in col_groups:
            sub = test[(test["model"] == model) & (test["setting"] == s)
                       & (test["horizon"] == h)]
            for metric, spec in metrics:
                if len(sub) == 0:
                    row.append("--")
                    continue
                v = sub[metric].iloc[0]
                cell = fmt(v, spec)
                # Bold if this is the best in its column
                if not pd.isna(v) and np.isclose(
                    v, best[(s, h, metric)], rtol=1e-9, atol=1e-9,
                ):
                    cell = rf"\textbf{{{cell}}}"
                row.append(cell)
        lines.append(" & ".join(row) + r" \\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    out_path.write_text("\n".join(lines) + "\n")


def write_multi_vs_global(df, out_path):
    """How much does multi-site help vs global, per (model, horizon)?"""
    test = df[df["split"] == "test"].copy()
    if not {"global", "multi"}.issubset(test["setting"].unique()):
        out_path.write_text("% multi-vs-global table unavailable\n")
        return

    pivot = test.pivot_table(index=["model", "horizon"], columns="setting",
                              values="MAE")
    pivot = pivot.reindex(columns=["global", "multi"])
    pivot[r"$\Delta$"] = pivot["multi"] - pivot["global"]
    pivot = pivot.reset_index()
    pivot["model"] = pivot["model"].map(lambda m: MODEL_LABEL.get(m, m))
    pivot = pivot.sort_values(["model", "horizon"])

    lines = []
    lines.append("% Auto-generated by src/make_latex_tables.py")
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(r"\caption{Effect of multi-site context on test MAE "
                 r"($\mu g/m^3$). Negative $\Delta$ means multi-site is "
                 r"better than global.}")
    lines.append(r"\label{tab:multi}")
    lines.append(r"\small")
    lines.append(r"\begin{tabular}{llrrr}")
    lines.append(r"\toprule")
    lines.append(r"\textbf{Model} & \textbf{Horizon} & "
                 r"\textbf{global} & \textbf{multi-site} & "
                 r"\boldmath$\Delta$\textbf{ (multi$-$global)} \\")
    lines.append(r"\midrule")
    for _, row in pivot.iterrows():
        d = row[r"$\Delta$"]
        d_str = f"{d:+.2f}"
        if pd.notna(d) and d < 0:
            d_str = rf"\textbf{{{d_str}}}"
        lines.append(
            f"{row['model']} & {int(row['horizon'])} h & "
            f"{fmt(row['global'])} & {fmt(row['multi'])} & {d_str} \\\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    out_path.write_text("\n".join(lines) + "\n")


def write_per_station(out_path):
    """Per-station MAE for the best sequence model (multi, h=1).
    Reads results/metrics/per_station.csv if it exists."""
    csv = config.METRICS_DIR / "per_station.csv"
    if not csv.exists():
        out_path.write_text(
            "% per_station.csv not yet generated\n"
            "\\noindent\\emph{Per-station table will appear after "
            "\\texttt{src.analyze\\_predictions} has been run.}\n"
        )
        return

    df = pd.read_csv(csv)
    # Try GRU first, then the other sequence models
    candidates = [
        ("gru", "multi", 1), ("transformer", "multi", 1), ("lstm", "multi", 1),
        ("gru", "global", 1), ("transformer", "global", 1),
    ]
    sub = None
    chosen = None
    for m, s, h in candidates:
        cand = df[(df["model"] == m) & (df["setting"] == s) & (df["horizon"] == h)]
        if len(cand):
            sub = cand
            chosen = (m, s, h)
            break
    if sub is None:
        out_path.write_text("% no sequence-model rows in per_station.csv\n")
        return

    sub = sub.sort_values("MAE")
    m, s, h = chosen
    lines = []
    lines.append("% Auto-generated by src/make_latex_tables.py")
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(
        rf"\caption{{Per-station test MAE for the {MODEL_LABEL.get(m, m)} model "
        rf"in the {SETTING_LABEL[s]} setting at $h{{=}}{h}$. Stations are sorted by error.}}"
    )
    lines.append(r"\label{tab:perstation}")
    lines.append(r"\small")
    lines.append(r"\begin{tabular}{lrrr}")
    lines.append(r"\toprule")
    lines.append(r"\textbf{Station} & \textbf{MAE} & \textbf{RMSE} & "
                 r"\textbf{Test hours} \\")
    lines.append(r"\midrule")
    for _, row in sub.iterrows():
        lines.append(
            f"{row['station']} & {fmt(row['MAE'])} & {fmt(row['RMSE'])} & "
            f"{int(row['n'])} \\\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    out_path.write_text("\n".join(lines) + "\n")


def copy_figures():
    """Copy PNGs from results/figures/ -> report/figures/."""
    src_figs = list(config.FIGURES_DIR.glob("*.png"))
    for src in src_figs:
        shutil.copy2(src, REPORT_FIG_DIR / src.name)
    print(f"copied {len(src_figs)} figures into {REPORT_FIG_DIR}")


def stub_missing_figures():
    """Create tiny placeholder PNGs for any figure referenced in report.tex
    that hasn't been generated yet. Keeps pdflatex happy during partial
    runs."""
    import matplotlib.pyplot as plt
    referenced = [
        "comparison_MAE.png",
        "gru_multi_h1_scatter.png", "gru_multi_h6_scatter.png",
        "linear_global_h1_timeseries.png", "gru_multi_h1_timeseries.png",
        "gru_multi_h1_train_curve.png",
        "lstm_multi_h1_train_curve.png",
        "transformer_multi_h1_train_curve.png",
    ]
    for name in referenced:
        path = REPORT_FIG_DIR / name
        if path.exists():
            continue
        fig, ax = plt.subplots(figsize=(3, 1.5))
        ax.text(0.5, 0.5, f"[{name}]\nnot yet generated",
                ha="center", va="center")
        ax.set_axis_off()
        fig.savefig(path, dpi=80)
        plt.close(fig)


def main():
    csv = config.METRICS_DIR / "results.csv"
    if not csv.exists():
        raise SystemExit(f"missing {csv}; run src.run_experiments first")
    df = pd.read_csv(csv)

    write_main_results(df, TABLES_DIR / "main_results.tex")
    write_multi_vs_global(df, TABLES_DIR / "multi_vs_global.tex")
    write_per_station(TABLES_DIR / "per_station.tex")
    copy_figures()
    stub_missing_figures()

    print(f"wrote all LaTeX fragments to {TABLES_DIR}")


if __name__ == "__main__":
    main()
